[package]
name = "random_context"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_math = "0.8.1"
num = "0.4.0"
rand = "0.8.5"
rand_distr = "0.4.3"
wyhash = "0.5.0"
